# Makefile for l directory listing tool

# Use all CPU cores for parallel builds
MAKEFLAGS += -j$(shell sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 1)

VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "unknown")

PREFIX ?= $(HOME)/.local
DESTBINDIR = $(PREFIX)/bin
CONFIGDIR = $(HOME)/.config/l
CONFIG_FILE = config.toml
ZSH_COMPLETIONS = $(PREFIX)/share/zsh/site-functions
BASH_COMPLETIONS = $(PREFIX)/share/bash-completion/completions
# Sourced zsh integration (widget, highlighter, history search) — not
# completion definitions, so not installed to site-functions. When the
# checkout itself lives at $(PREFIX)/share/l (the dotfiles convention),
# source and destination coincide and the copy is skipped.
SHELL_DEST = $(PREFIX)/share/l/shell

# Local build output
BINDIR = bin

CC = cc
CFLAGS = -O2 -Wall -Wextra -std=c99 -DVERSION=\"$(VERSION)\"
LIBS = -lpthread -lz

# Cap on OpenMP threads (avoids thread-pool spin-up overhead on many-core
# machines). Override with `make MAX_THREADS=N`; set to 0 for no cap.
MAX_THREADS ?= 8

# OpenMP support (use homebrew clang on macOS)
UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
  # Check for homebrew llvm (Apple clang doesn't support OpenMP)
  BREW_LLVM := $(shell brew --prefix llvm 2>/dev/null)
  ifneq ($(BREW_LLVM),)
    CC = $(BREW_LLVM)/bin/clang
    CFLAGS += -fopenmp
  endif
else
  # Linux needs _GNU_SOURCE for O_DIRECTORY, fdopendir, fstatat, etc.
  CFLAGS += -fopenmp -D_GNU_SOURCE -D_DEFAULT_SOURCE
endif

# Optional libgit2 support
HAVE_LIBGIT2 := $(shell pkg-config --exists libgit2 2>/dev/null && echo yes)
ifeq ($(HAVE_LIBGIT2),yes)
  CFLAGS += -DHAVE_LIBGIT2 $(shell pkg-config --cflags libgit2)
  LIBS += $(shell pkg-config --libs libgit2)
endif

# Optional sqlite support (auto-detected; override with `make HAVE_SQLITE=no`).
# Without it, l builds with no size cache and l-cached is not built; otherwise
# unchanged. -DHAVE_SQLITE is appended after the DEBUG reset (see below) so it
# survives both build modes; the link libs are added here (LIBS is not reset).
SQLITE_DETECTED := $(shell pkg-config --exists sqlite3 2>/dev/null && echo yes || echo no)
HAVE_SQLITE ?= $(SQLITE_DETECTED)
ifeq ($(HAVE_SQLITE),yes)
  SQLITE_CFLAGS := $(shell pkg-config --cflags sqlite3)
  LIBS += $(shell pkg-config --libs sqlite3)
endif

# Debug build
ifdef DEBUG
  CFLAGS = -g -O0 -Wall -Wextra -std=c99 -fsanitize=address,undefined -DDEBUG
  CFLAGS += -fopenmp
  ifeq ($(HAVE_LIBGIT2),yes)
    CFLAGS += -DHAVE_LIBGIT2 $(shell pkg-config --cflags libgit2)
  endif
endif

# Thread cap (applied after the DEBUG reset so it affects both builds)
CFLAGS += -DL_MAX_THREADS=$(MAX_THREADS)

# SQLite define (applied after the DEBUG reset so it affects both builds)
ifeq ($(HAVE_SQLITE),yes)
  CFLAGS += -DHAVE_SQLITE $(SQLITE_CFLAGS)
endif

# Source directory
SRCDIR = src

# Object files (in src/)
COMMON_OBJS = $(SRCDIR)/common.o
CACHE_CLIENT_OBJS = $(SRCDIR)/cache.o
CACHE_DAEMON_OBJS = $(SRCDIR)/cache_daemon.o
SCAN_OBJS = $(SRCDIR)/scan.o
GIT_OBJS = $(SRCDIR)/git.o
TREE_OBJS = $(SRCDIR)/tree.o
UI_OBJS = $(SRCDIR)/view.o $(SRCDIR)/render.o $(SRCDIR)/icons.o $(SRCDIR)/fileinfo.o $(SRCDIR)/config.o $(SRCDIR)/format.o
DAEMON_OBJS = $(SRCDIR)/daemon.o
SELECT_OBJS = $(SRCDIR)/select.o

# Main targets (l-cached is only built when SQLite is available)
BINARIES = $(BINDIR)/l $(BINDIR)/cl
ifeq ($(HAVE_SQLITE),yes)
  BINARIES += $(BINDIR)/l-cached
endif

all: $(BINARIES)

$(BINDIR):
	mkdir -p $(BINDIR)

$(BINDIR)/l: $(SRCDIR)/l.o $(COMMON_OBJS) $(CACHE_CLIENT_OBJS) $(SCAN_OBJS) $(GIT_OBJS) $(TREE_OBJS) $(UI_OBJS) $(DAEMON_OBJS) $(SELECT_OBJS) | $(BINDIR)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

$(BINDIR)/l-cached: $(SRCDIR)/ld.o $(COMMON_OBJS) $(CACHE_DAEMON_OBJS) $(SCAN_OBJS) | $(BINDIR)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

$(BINDIR)/cl: $(SRCDIR)/cl | $(BINDIR)
	ln -sf ../$(SRCDIR)/cl $@

# Object files. Header dependencies are generated by the compiler (-MMD -MP,
# included below): hand-maintained lists silently go stale — a missing entry
# links objects compiled against different struct layouts.
$(SRCDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -MMD -MP -c -o $@ $<

-include $(SRCDIR)/*.d

install: all
	@mkdir -p $(DESTBINDIR)
	@mkdir -p $(CONFIGDIR)
	install -m 755 $(BINDIR)/l $(DESTBINDIR)/l
ifeq ($(HAVE_SQLITE),yes)
	install -m 755 $(BINDIR)/l-cached $(DESTBINDIR)/l-cached
endif
	install -m 755 $(SRCDIR)/cl $(DESTBINDIR)/cl
ifeq ($(HAVE_SQLITE),yes)
	@echo "Installed l, l-cached, and cl to $(DESTBINDIR)"
else
	@echo "Installed l and cl to $(DESTBINDIR) (without SQLite; l-cached not built)"
endif
	@if [ -f $(CONFIGDIR)/$(CONFIG_FILE) ] && [ -z "$(OVERWRITE_CONFIG)" ]; then \
		echo "Kept existing $(CONFIG_FILE) in $(CONFIGDIR) (not overwritten; use OVERWRITE_CONFIG=1 to replace)"; \
	else \
		install -m 644 $(CONFIG_FILE) $(CONFIGDIR)/$(CONFIG_FILE); \
		echo "Installed $(CONFIG_FILE) to $(CONFIGDIR)"; \
	fi
	@mkdir -p $(ZSH_COMPLETIONS)
	install -m 644 completions/_l $(ZSH_COMPLETIONS)/_l
	install -m 644 completions/_cl $(ZSH_COMPLETIONS)/_cl
	@echo "Installed zsh completions to $(ZSH_COMPLETIONS)"
	@mkdir -p $(SHELL_DEST)
	@if [ "$$(cd shell && pwd -P)" != "$$(cd $(SHELL_DEST) && pwd -P)" ]; then \
		install -m 644 shell/l-widget.zsh shell/zhl.zsh shell/l-history.zsh $(SHELL_DEST)/; \
		echo "Installed zsh shell integration to $(SHELL_DEST)"; \
	else \
		echo "Shell integration is sourced from the checkout ($(SHELL_DEST))"; \
	fi
	@if command -v zsh >/dev/null 2>&1 && ! zsh -ic 'echo "$$fpath"' 2>/dev/null | grep -qF "$(ZSH_COMPLETIONS)"; then \
		printf "\033[33mWarning:\033[0m $(ZSH_COMPLETIONS) is not in your zsh fpath\n"; \
		echo "  Add this to your .zshrc: fpath=($(ZSH_COMPLETIONS) \$$fpath)"; \
	fi
	@mkdir -p $(BASH_COMPLETIONS)
	install -m 644 completions/l.bash $(BASH_COMPLETIONS)/l
	ln -sf l $(BASH_COMPLETIONS)/cl
	@echo "Installed bash completions to $(BASH_COMPLETIONS)"
	@printf "\n\033[33mNote:\033[0m completion changes need a shell reload.\n"

uninstall:
	rm -f $(DESTBINDIR)/l $(DESTBINDIR)/l-cached $(DESTBINDIR)/cl
	rm -f $(CONFIGDIR)/$(CONFIG_FILE)
	rmdir $(CONFIGDIR) 2>/dev/null || true
	rm -f $(ZSH_COMPLETIONS)/_l $(ZSH_COMPLETIONS)/_cl
	rm -f $(ZSH_COMPLETIONS)/l-widget.zsh $(ZSH_COMPLETIONS)/zhl.zsh $(ZSH_COMPLETIONS)/l-history.zsh
	@if [ -d shell ] && [ -d $(SHELL_DEST) ] && [ "$$(cd shell && pwd -P)" != "$$(cd $(SHELL_DEST) && pwd -P)" ]; then \
		rm -f $(SHELL_DEST)/l-widget.zsh $(SHELL_DEST)/zhl.zsh $(SHELL_DEST)/l-history.zsh; \
		rmdir $(SHELL_DEST) 2>/dev/null || true; \
	fi
	rm -f $(BASH_COMPLETIONS)/l $(BASH_COMPLETIONS)/cl
	@echo "Uninstalled l"

clean:
	rm -f $(SRCDIR)/*.o $(SRCDIR)/*.d $(BINDIR)/l $(BINDIR)/l-cached $(BINDIR)/cl

# Recent clang-tidy enables no checks by default; pick the correctness-
# oriented families explicitly (style checks excluded on purpose).
# Suppressed as noise for this codebase:
#   multi-level-implicit-pointer-conversion  T** through malloc/free/memset
#                                            is idiomatic C
#   command-processor, optin.taint           popen/system are how the git
#                                            fallback, file openers, and
#                                            clipboard work; call sites
#                                            shell-escape or bind paths as $0
#   implicit-widening, unchecked-string-…    st_blocks*512-style arithmetic
#                                            and atoi on our own/git output
#   security.ArrayBound                      false-positives on the
#                                            s[strcspn(s,…)]='\0' idiom and
#                                            the clamped EMIT cursor
LINT_CHECKS = clang-diagnostic-*,clang-analyzer-*,bugprone-*,portability-*,-bugprone-easily-swappable-parameters,-bugprone-narrowing-conversions,-bugprone-multi-level-implicit-pointer-conversion,-bugprone-command-processor,-clang-analyzer-optin.taint.GenericTaint,-bugprone-implicit-widening-of-multiplication-result,-bugprone-unchecked-string-to-number-conversion,-clang-analyzer-security.ArrayBound

lint:
	clang-tidy --quiet -checks='$(LINT_CHECKS)' --header-filter='$(SRCDIR)/.*' \
		$(SRCDIR)/*.c -- -I$(SRCDIR) $(CFLAGS)

.PHONY: all install uninstall clean lint
